spring.application.name=API_REST

spring.datasource.url=jdbc:mysql://localhost:3306/productos
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
server.port=8081 
server.shutdown=graceful

spring.security.user.name=user
spring.security.user.password=12345

